apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelsftp
  namespace: travelspace

spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: travelsftp
  template:
    metadata:
      labels:
        app: travelsftp
    spec:
      containers:
        - name: sftp
          image: atmoz/sftp:latest
          ports:
            - containerPort: 22
          env:
            - name: SFTP_USERS
              valueFrom:
                secretKeyRef:
                  name: sftp-secret
                  key: users.conf
          volumeMounts:
            - name: sftp-users
              mountPath: /etc/sftp
              subPath: users.conf
            - name: sftp-data
              mountPath: /home/data

      volumes:
        - name: sftp-users
          secret:
            secretName: sftp-secret
        - name: sftp-data
          persistentVolumeClaim:
           claimName: sftp-pvc