spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_data?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: travel
    password: travel!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

  jackson:
    serialization:
      write-dates-as-timestamps: false

    date-format: yyyy-MM-dd'T'HH:mm:ss

  mail:
    host: smtp.travel.com
    port: 587
    username: travel
    password: travelEmail12!
    properties:
      from: travelProcessor@trp.com
      mail:
        smtp:
          auth: true


mybatis:
  type-aliases-package: org.abondar.experimental.travel.model.db
  mapper-locations: classpath:mapper/*Mapper.xml

sftp:
  host: localhost
  port: 22
  username: fUser
  password: fPass
  enabled: false


email:
  enabled: false
  to: abondar24@yahoo.com
  subject: "Travel data report at: "


file:
  hotel: data/hotel/hotel_bookings.json
  flight: data/flight/flight_bookings.csv
  cruise: data/cruise/cruise_bookings.xml
