spring:
  datasource:
    url: jbdc:mysql://localhost:3306/travel_data?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: travel
    password: travel1@#
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: org.abondar.exerimental.travel.model.db
  mapper-locations: classpath:mybatis/mapper/*mapper.xml