spring:
  datasource:
   url: jdbc:mysql://${DB_HOST}:${DB_PORT}/travel_data?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
   username: ${DB_USER}
   password: ${DB_PASS}


  mail:
   host: ${SMTP_HOST}

  batch:
    job:
      name: ${JOB_NAME}



sftp:
 host: ${SFTP_HOST}