apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveldb
  namespace: travelspace

spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: traveldb
  template:
    metadata:
      labels:
        app: traveldb
    spec:
      containers:
        - name: traveldb
          image: mysql:8.4.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc