apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveldb
  namespace: travelspace

spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: traveldb
  template:
    metadata:
      labels:
        app: traveldb
    spec:
      containers:
        - name: traveldb
          image: mysql:8.4.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc