INSERT INTO city (name) VALUES
                            ('Vienna'),
                            ('Brussels'),
                            ('Sofia'),
                            ('Zagreb'),
                            ('Prague'),
                            ('Copenhagen'),
                            ('Tallinn'),
                            ('Helsinki'),
                            ('Paris'),
                            ('Berlin'),
                            ('Athens'),
                            ('Budapest'),
                            ('Dublin'),
                            ('Rome'),
                            ('Riga'),
                            ('Vilnius'),
                            ('Luxembourg City'),
                            ('Valletta'),
                            ('Amsterdam'),
                            ('Warsaw'),
                            ('Lisbon'),
                            ('Bucharest'),
                            ('Moscow'),
                            ('San Marino'),
                            ('Belgrade'),
                            ('Bratislava'),
                            ('Ljubljana'),
                            ('Madrid'),
                            ('Stockholm'),
                            ('Bern');